a=None
b=10
c=10.10
d='true'
e='abcdef'
element=[1,2,3,4,5,6]
f=bytes(element)
g=bytearray(element)
h=[1,'nerrow',3,3,3,"bann"]
i=("gir","java","python")
j=list(range(1,100,25))
k={12,40,80,5,8}
l={1:'kreya',2:'rahu',3:'mohan'}
print(type(a),a)
print(type(b),b)
print(type(c),c)
print(type(d),d)
print(type(e),e)
print(type(f),f)
print(type(g),g)
print(type(h),h)
print(type(i),i)
print(type(j),j)
print(type(k),k)
print(type(l),l)
